### ISSUE TITLE
Slashes in course names are parsed incorrectly

### ISSUE THREAD

**Issue by n-st** [fknorr/studip-client#11]
The course title "Fachschaft für Informatik und Mathematik / IEEE (WS 07/08 - unbegrenzt) (Veranstaltungsboard)" produces the following directory structure:

    └── Fachschaft für Informatik und Mathematik 
        └──  IEEE (WS 07
             └── 08 - unbegrenzt) (Veranstaltungsboard)

**Comment by fknorr** [comment]
Same problem for directories, which may also contain slashes

**Comment by fknorr** [comment]
Slashes in directories are now correctly detected and escaped as long as there are no spaces around them (`" / "`). Closing this as there is no realistic chance of a workaround without increasing the number of requests significantly.
