### ISSUE TITLE
Allow customizing the download path and filename

### ISSUE THREAD

**Issue by n-st** [fknorr/studip-client#12]
Provide the user with an option to specify a custom download path for the files, e.g. based on placeholders for

* semester
* course title
* course type (lecture, exercise, …)
* file title
* filename
* file extension

**Comment by N-Coder** [comment]
You could also let the user specify conditions for rewriting the paths, so that different lectures could have different directory structures. This could also be a fix for #7.
Maybe you can port the [apache httpd mod_rewrite](https://httpd.apache.org/docs/2.0/misc/rewriteguide.html). :joy:

**Comment by fknorr** [comment]
Now possible via the `path_format` setting. Documentation will follow.
